name: Premium server
on:
  workflow_dispatch: # Chạy bằng tay khi bạn muốn

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Install tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"
          Start-Process -FilePath "tailscale-setup.exe" -ArgumentList "/quiet", "/norestart" -Wait
          
      - name: Connect to tailscale
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey ${{ secrets.TAILSCALE_AUTHKEY }}
          
      - name: Create user
        run: |
          $User = "server_premium"
          $Pass = "server_premium" 
          net user $User $Pass /add
          net localgroup administrators $User /add
          net localgroup "Remote Desktop Users" $User /add

      - name: AntiVM
        run: |
          reg add "HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\CentralProcessor\0" /v "ProcessorNameString" /t REG_SZ /d "Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz" /f
          reg add "HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\BIOS" /v "SystemManufacturer" /t REG_SZ /d "ASUSTeK COMPUTER INC." /f
          reg add "HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\BIOS" /v "SystemProductName" /t REG_SZ /d "ROG STRIX Z490-E GAMING" /f
          Set-Service -Name "VMTools" -Status Stopped -ErrorAction SilentlyContinue

      - name: 5. Tải sẵn Roblox và Hiện IP
        run: |
          Write-Host "------------------------------------------"
          $tsIP = (Get-NetIPAddress -InterfaceAlias 'Tailscale' -AddressFamily IPv4).IPAddress
          Write-Host "IP ĐỂ KẾT NỐI: $tsIP"
          Write-Host "User: server_premium | Pass: server_premium"
          Write-Host "------------------------------------------"

      - name: 6. Duy trì máy (6 tiếng)
        run: |
          $seconds = 21600
          for ($i = 0; $i -lt $seconds; $i += 10) {
            Write-Host "Đang chạy... $i / $seconds giây"
            Start-Sleep -Seconds 10
          }
