name: Premium server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Create user
        shell: powershell
        run: |
          $User = "ServerPremium"
          $Pass = "ServerPre@123"

          net user $User $Pass /add
          net localgroup administrators $User /add
          net localgroup "Remote Desktop Users" $User /add

      - name: Show credentials
        shell: powershell
        run: |
          Write-Host ""
          Write-Host "=========================================="
          Write-Host "RDP Host : ${{ secrets.CF_HOSTNAME }}"
          Write-Host "User     : ServerPremium"
          Write-Host "Password : ServerPre@123"
          Write-Host "=========================================="
          Write-Host ""

      - name: Install Applications
        shell: cmd
        run: |
          choco feature enable -n allowGlobalConfirmation
          choco install cloudflared intellijidea-community --no-progress

      - name: Start Cloudflare Tunnel
        shell: powershell
        run: cloudflared.exe service install ${{ secrets.CF_TOKEN }}

      - name: Keep alive
        shell: powershell
        run: |
          $seconds = 21500

          for ($i = 0; $i -lt $seconds; $i += 10) {
              Write-Host "Running... $i / $seconds seconds"
              Start-Sleep -Seconds 10
          }
